name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build: #id job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world desde workflow!
        
  referencia_action: #id job
    runs-on: ubuntu-latest
    needs: build #hasta que no se termine build, no comienza el nuevo job
    steps:
      - name: run action
        uses: acalderon-dvp/actions@v1
